# docker-compose.yml
version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/frontend/app
      - node_modules:/app/node_modules

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
volumes:
  node_modules:
